### ISSUE TITLE
Openserach Security Auth Type fails for multi auth configuration

### ISSUE THREAD

**Issue by ericklife28** [opensearch-project/opensearch-k8s-operator#689]
### What is the bug?
When I try to configure multi auth configuration using these entries:
dashboards:
  additionalConfig:
        opensearch_security.auth.type: '[\"basicauth\",\"openid\"]'
        opensearch_security.auth.multiple_auth_enabled: "true"

I get this error from opensearch-cluster-dashboards pod 

{"type":"log","@timestamp":"2023-12-23T13:21:15Z","tags":["fatal","root"],"pid":1,"message":"ValidationError: [config validation of [opensearch_security].auth.type]: expected value of type [string] but got [Array]\n    at ObjectType.validate (/usr/share/opensearch-dashboards/node_modules/@osd/config-schema/target/out/types/type.js:72:19)\n    at ConfigService.validateAtPath (/usr/share/opensearch-dashboards/node_modules/@osd/config/target/config_service.js:157:23)\n    at MapSubscriber.project (/usr/share/opensearch-dashboards/node_modules/@osd/config/target/config_service.js:164:83)\n    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:49:35)\n    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at DistinctUntilChangedSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30)\n    at DistinctUntilChangedSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:55:26)\n    at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n    at ReplaySubject._subscribe (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/ReplaySubject.js:80:28)\n    at ReplaySubject.Observable._trySubscribe (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Observable.js:44:25)\n    at ReplaySubject.Subject._trySubscribe (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subject.js:102:51)\n    at ReplaySubject.Observable.subscribe (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Observable.js:30:22)\n    at MapSubscriber.shareReplayOperation (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/shareReplay.js:53:32)\n    at Observable.subscribe (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Observable.js:25:31)\n    at MapOperator.call (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:32:23) {\n  cause: SchemaTypeError: expected value of type [string] but got [Array]\n      at StringType.onError (/usr/share/opensearch-dashboards/node_modules/@osd/config-schema/target/out/types/type.js:102:20)\n      at type.<anonymous> (/usr/share/opensearch-dashboards/node_modules/@osd/config-schema/target/out/types/type.js:62:53)\n      at finish (/usr/share/opensearch-dashboards/node_modules/joi/lib/types/any/index.js:529:50)\n      at type._validate (/usr/share/opensearch-dashboards/node_modules/joi/lib/types/any/index.js:656:28)\n      at type._base (/usr/share/opensearch-dashboards/node_modules/joi/lib/types/object/index.js:212:45)\n      at type._validate (/usr/share/opensearch-dashboards/node_modules/joi/lib/types/any/index.js:614:37)\n      at type._base (/usr/share/opensearch-dashboards/node_modules/joi/lib/types/object/index.js:212:45)\n      at type._validate (/usr/share/opensearch-dashboards/node_modules/joi/lib/types/any/index.js:614:37)\n      at type._validateWithOptions (/usr/share/opensearch-dashboards/node_modules/joi/lib/types/any/index.js:674:29)\n      at module.exports.internals.Any.root.validate (/usr/share/opensearch-dashboards/node_modules/joi/lib/index.js:146:23)\n      at ObjectType.validate (/usr/share/opensearch-dashboards/node_modules/@osd/config-schema/target/out/types/type.js:67:72)\n      at ConfigService.validateAtPath (/usr/share/opensearch-dashboards/node_modules/@osd/config/target/config_service.js:157:23)\n      at MapSubscriber.project (/usr/share/opensearch-dashboards/node_modules/@osd/config/target/config_service.js:164:83)\n      at MapSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/map.js:49:35)\n      at MapSubscriber.Subscriber.next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/Subscriber.js:66:18)\n      at DistinctUntilChangedSubscriber._next (/usr/share/opensearch-dashboards/node_modules/rxjs/internal/operators/distinctUntilChanged.js:69:30) {\n    cause: undefined,\n    path: [ 'auth', 'type' ]\n  }\n}"}

 FATAL  Error: [config validation of [opensearch_security].auth.type]: expected value of type [string] but got [Array]

Stream closed EOF for opensearch-cluster/opensearch-cluster-dashboards-6cbbfdc5d9-tz7zc (dashboards)

### How can one reproduce the bug?
 Using the configuration above for the opensearch-cluster helm chart and executing it.  

### What is the expected behavior?
The opensearch-cluster-dashboards pod start up shouldn't fail.

### Do you have any additional context?
I am using the opensearch-cluster helm chart to apply this configuration.

**Comment by oleksii-kalinin** [comment]
Works for me with this syntax
```yaml
    additionalConfig:
      opensearch_security.auth.anonymous_auth_enabled: "false"
      opensearch_security.auth.type: |
        ["openid", "basicauth"]
```

**Comment by SakibAbrar** [comment]
@oleksii-kalinin any idea how to enable? anonymous_auth? 
Just allowing opensearch_security.auth.anonymous_auth_enabled: "true" doesn't work

**Comment by applejag** [comment]
I had this issue too, and eventually figured out that I was using a really old version of OpenSearch.

The Helm chart by default uses a really old version:

https://github.com/opensearch-project/opensearch-k8s-operator/blob/d6dce307a8f7069d221762d476b434da7bea13be/charts/opensearch-cluster/values.yaml#L113-L114

So by setting the version to something newer then I could set the multi-auth config:

```yaml
cluster:
  general:
    version: &version 3.2.0

  dashboards:
    version: *version

    additionalConfig:
      opensearch_security.auth.anonymous_auth_enabled: "false"
      opensearch_security.auth.type: '["openid", "basicauth"]'
      opensearch_security.auth.multiple_auth_enabled: "true"
```

Personally I was unable to upgrade an existing OpenSearch cluster, but I had the possibility of just recreating the cluster instead which worked.

**Comment by synhershko** [comment]
Config error; working auth.type array-string config posted in-thread. Not an operator bug. Closing.
